### ISSUE TITLE
Got this error with the simple test

### ISSUE THREAD

**Issue by SpaceboyRoss01** [viert/z80js#1]
```
Thrown:
TypeError: Cannot read property 'toString' of undefined
    at o (/home/spaceboyross/z80vm/node_modules/z80js/index.js:1:1318)
    at hex8 (/home/spaceboyross/z80vm/node_modules/z80js/index.js:1:1498)
    at dasm.Error disassembling .i.map.t (/home/spaceboyross/z80vm/node_modules/z80js/index.js:1:12535)
    at Array.map (<anonymous>)
    at x.disassemble (/home/spaceboyross/z80vm/node_modules/z80js/index.js:1:12528)
    at Z80.run (/home/spaceboyross/z80vm/z80.js:91:28)
    at Timeout._intv.setInterval [as _onTimeout] (/home/spaceboyross/z80vm/z80.js:78:21)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
```

**Comment by viert** [comment]
Hey there! Could you please provide a bit more info on your test? Looks like something is wrong with disassemble() function under certain circumstances which I'm not really aware of. What exactly does `/home/spaceboyross/z80vm/z80.js` do?

**Comment by SpaceboyRoss01** [comment]
https://github.com/SpaceboyRoss01/micro8/blob/master/emulatorjs/index.js This is what it does. And this is an error it provides:
```
TypeError: Cannot read property 'toString' of undefined
    at o (/home/spaceboyross/micro8/emulatorjs/node_modules/z80js/index.js:1:1318)
    at hex8 (/home/spaceboyross/micro8/emulatorjs/node_modules/z80js/index.js:1:1498)
    at x.read8.i [as read8] (/home/spaceboyross/micro8/emulatorjs/node_modules/z80js/index.js:1:3137)
    at x.ld_a__bc_ (/home/spaceboyross/micro8/emulatorjs/node_modules/z80js/index.js:1:23504)
    at x.execute (/home/spaceboyross/micro8/emulatorjs/node_modules/z80js/index.js:1:13767)
    at cycle (/home/spaceboyross/micro8/emulatorjs/index.js:44:11)
    at Object.start (/home/spaceboyross/micro8/emulatorjs/index.js:77:11)
    at repl:1:10
    at Script.runInThisContext (vm.js:124:20)
    at REPLServer.defaultEval (repl.js:322:29)
```

**Comment by SpaceboyRoss01** [comment]
```
ld a, (bc)
CPU debug: execute() started, t = 5670
CPU debug: Reading memory address 0x0CEE = 0x0A
CPU debug: memory read, t = 5673
CPU debug: pc incremented, t = 5674
CPU debug: Running ld_a__bc_(), t = 5674
```
This is what the debug says

**Comment by viert** [comment]
I think I got it after all. This is because your implementation of read8 returns undefined value at some point which is not how it's supposed to work in real hardware. I believe you hit the bounds of the memory array so the reader returns undefined. I added a log message to make it more clear, however I'm quite sure it's ok to throw an exception in such cases.
